config/routes.rb
require 'sidekiq/web'

GetLead::Application.routes.draw do

  devise_for :users, except: [:create, :new, :update]

  match 'notifications/:id/hide', to: 'notifications#hide', as: 'hide_notification', via: :get

  resources :progresses
  resources :users do
    collection { post :file_uploads}
    collection { post :phones}
    collection { post :send_broadcast}
  end

  mount Sidekiq::Web, at: '/sidekiq'

  mount MongodbLogger::Server.new, :at => "/mongodb", :as => :mongodb
  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

  resources :reports

  resources :leads do
    collection { post :import }
    collection { get :import }
  end

  require 'api_constraints'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :leads
    end
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      resources :leads do
        collection { post :statistics }
      end
      patch '/leads/update' => 'leads_controller#update', as: 'update_leads'
    end
  end

   root :to => 'leads#index'

end

app/controllers/progresses_controller.rb
# -*- encoding : utf-8 -*-
class ProgressesController < ApplicationController
  before_action :set_progress, only: [:show, :edit, :update, :destroy]

  # GET /progresses
  # GET /progresses.json
  def index
    @progresses = Progress.all
  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
  end

  # GET /progresses/new
  def new
    @progress = Progress.new
  end

  # GET /progresses/1/edit
  def edit
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'Progress was successfully created.' }
        format.json { render action: 'show', status: :created, location: @progress }
      else
        format.html { render action: 'new' }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      if @progress.update(progress_params)
        format.html { redirect_to @progress, notice: 'Progress was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @progress }
      else
        format.html { render action: 'edit' }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @progress.destroy
    respond_to do |format|
      format.html { redirect_to progresses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_progress
      @progress = Progress.find_or_create_by(user_id: current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def progress_params
      params.require(:progress).permit(:value, :user_id, :source, :model)
    end
end

app/helpers/progresses_helper.rb
# -*- encoding : utf-8 -*-
module ProgressesHelper
end

app/views/progresses/edit.html.erb
<h1>Editing progress</h1>

<%= render 'form' %>

<%= link_to 'Show', @progress %> |
<%= link_to 'Back', progresses_path %>

app/views/progresses/index.html.erb
<h1>Listing progresses</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>User</th>
      <th>Source</th>
      <th>Model</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @progresses.each do |progress| %>
      <tr>
        <td><%= progress.value %></td>
        <td><%= progress.user_id %></td>
        <td><%= progress.source %></td>
        <td><%= progress.model %></td>
        <td><%= link_to 'Show', progress %></td>
        <td><%= link_to 'Edit', edit_progress_path(progress) %></td>
        <td><%= link_to 'Destroy', progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Progress', new_progress_path %>

app/views/progresses/new.html.erb
<h1>New progress</h1>

<%= render 'form' %>

<%= link_to 'Back', progresses_path %>

app/views/progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @progress.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @progress.user_id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @progress.source %>
</p>

<p>
  <strong>Model:</strong>
  <%= @progress.model %>
</p>

<%= link_to 'Edit', edit_progress_path(@progress) %> |
<%= link_to 'Back', progresses_path %>