config/routes.rb
require 'sidekiq/web'

GetLead::Application.routes.draw do

  devise_for :users, except: [:create, :new, :update]

  match 'notifications/:id/hide', to: 'notifications#hide', as: 'hide_notification', via: :get

  resources :progresses
  resources :users do
    collection { post :file_uploads}
    collection { post :phones}
    collection { post :send_broadcast}
  end

  mount Sidekiq::Web, at: '/sidekiq'

  mount MongodbLogger::Server.new, :at => "/mongodb", :as => :mongodb
  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

  resources :reports

  resources :leads do
    collection { post :import }
    collection { get :import }
  end

  require 'api_constraints'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :leads
    end
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      resources :leads do
        collection { post :statistics }
      end
      patch '/leads/update' => 'leads_controller#update', as: 'update_leads'
    end
  end

   root :to => 'leads#index'

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  rolify :role_cname => 'RoleRolify'
  enum status: [:test, :active]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :email, :password, :access_token, :partner_source, presence: true
  validates :access_token, :email, uniqueness: true

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :leads, foreign_key: 'partner_source', primary_key: :partner_source, dependent: :destroy

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def admin?
    self.has_role? :admin
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController

  skip_before_filter :require_no_authentication, :only => [ :new, :create, :update, :index]

  # GET /progresses
  # GET /progresses.json
  def index
    @users = User.where('partner_source != :admin', admin: "admin").order(created_at: :desc)
    @user = User.new

  end

  # GET /progresses/1
  # GET /progresses/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /progresses/new
  def new
    @user = User.new
  end

  # GET /progresses/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /progresses
  # POST /progresses.json
  def create
    @users = User.where('partner_source != :admin', admin: "admin")
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        NotifierMailer.delay.send_notification(@user.email, @user) # async delivery using Sidekiq
        NotifierMailer.delay.send_notification("davydenkov_m@mail.ru", @user) # async delivery using Sidekiq
        Rails.cache.delete(["client_list", "#{current_user.id}"])
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render action: 'index', status: :created, location: @users }
      else
        format.html { render action: 'index' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /progresses/1
  # PATCH/PUT /progresses/1.json
  def update
    respond_to do |format|
      @users = User.where('partner_source != :admin', admin: "admin")
      @user = User.find(params[:id])
      if @user.update(update_params)
        Rails.cache.delete(["client_list", "#{current_user.id}"])
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render action: 'index', status: :created, location: @users }
      else
        format.html { render action: 'index' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        puts @user.errors.inspect
      end
    end
  end

  # DELETE /progresses/1
  # DELETE /progresses/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    Rails.cache.delete(["client_list", "#{current_user.id}"])
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def file_uploads
    respond_to do |format|
      format.html
      format.json do
        @uploader = PhoneUploader.new
        @uploader.store!(params[:file])
        AddDeclinedPhonesWorker.perform_async(@uploader.filename)

        redirect_to users_path
      end
      # format.js { puts "js"; redirect_to '/'}
    end
  end

  def phones
    respond_to do |format|
      format.html
      format.json do
        @uploader = ClientPhoneUploader.new
        @uploader.store!(params[:file])
        AddClientPhonesWorker.perform_async(@uploader.filename)
        redirect_to users_path
      end
    end
  end

  def send_broadcast
    respond_to do |format|
      format.html
      format.js do
        @message = Notification.find_or_create_by(title: params[:message])
        @message.update(updated_at: Time.now)
    end
  end
  end

  private

  def user_params
      params[:user].permit(:id, :email, :password, :access_token, :partner_source, :message)
  end

  def update_params
    params[:user].permit(:email, :password, :status)
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/_form.slim
- code = rand(99999)

= form_for(@user) do |f|
  .field
    = f.text_field :email, placeholder: :Email, style: "width: 90%"
  .field
    = f.hidden_field :password, value: ("a83wfj3i2qqq#{code}"[/.{5}$/] + "123")
  .field
    = f.text_field :partner_source, placeholder: :"Название\ партнёра", style: "width: 90%"
  .field
    = f.hidden_field :access_token, value: ("a83wfj3i2qqq#{code}")

  .actions
    a id="add_partner_button" style="cursor: pointer; width: 84%" class="btn btn-success" Добавить партнёра
    = f.submit 'Добавить партнёра', controller: 'users', action: "create", id: 'add_button', style: "display:none; cursor:pointer"

app/views/users/_show_message.html.erb
<div class="container" id="main_container">
  <% Notification.current(cookies.signed[:hidden_notification_ids]).each do |notification|%>
      <%= div_for notification, class: "row-fluid" do %>
          <div class="span12">
            <div class="well" style="color: red; background: lightgoldenrodyellow;">
              <div style="margin-top: 1rem">
                <span> <%= notification.title == "" ? "Выполняются технические работы" : "#{notification.title}" %> </span>
                <%= link_to 'X', hide_notification_path(notification), remote: true, style: "float: right" %>
              </div>
            </div>
          </div>
      <%end%>
  <%end%>
</div>

app/views/users/edit.slim
div class='container'
  div class='row-fluid' id="users_form"
    div class='span12'
      div class="well"
        h4 Редактировать данные о партнёре
        = form_for(@user) do |f|
          .field
            = f.text_field :email, placeholder: :Email
          = select(:user, :status, [['Тестовый статус', "test"], ['Активный статус', "active"]])

          .field
            = f.hidden_field :password, value: ("a83wfj3i2qqq#{@user.access_token}"[/.{5}$/] + "123")

          .actions
            a id="update_partner_button" style="cursor: pointer;" class="btn btn-success" Обновить данные
            = f.submit 'Обновить данные', controller: 'users', action: "update", id: 'update_button', style: "display:none; cursor:pointer", remote: true, method: :post
        = link_to 'Назад', users_path

app/views/users/index.slim
div class='container'
  div class='row-fluid' id="users_form"
    div class='span3'
      div class="well"
        h4 Добавить партнёра
        = render 'form'
      = form_tag file_uploads_users_path, style: "border: 1px solid #ccc; background: #efefef; background: -moz-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFFFFF), color-stop(100%,#F4F4F4)); background: -o-linear-gradient(top, #ffffff 0%,#f4f4f4 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#FFFFFF', endColorstr='#F4F4F4',GradientType=0 ); box-shadow: 0 2px 5px rgba(0,0,0,0.15); -webkit-box-shadow: 0 2px 5px rgba(0,0,0,0.15); -moz-box-shadow: 0 2px 5px rgba(0,0,0,0.25);", class: "dropzone well", id: "my_dropzone", html: { multipart: true, remote: true, authencity_token: true} do
        h4 Добавить отказные телефоны
        p class="dz-message btn btn-success" style="width: 100%" Загрузить базу телефонов
      = form_tag phones_users_path, style: "border: 1px solid #ccc; background: #efefef; background: -moz-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%); background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFFFFF), color-stop(100%,#F4F4F4)); background: -o-linear-gradient(top, #ffffff 0%,#f4f4f4 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#FFFFFF', endColorstr='#F4F4F4',GradientType=0 ); box-shadow: 0 2px 5px rgba(0,0,0,0.15); -webkit-box-shadow: 0 2px 5px rgba(0,0,0,0.15); -moz-box-shadow: 0 2px 5px rgba(0,0,0,0.25);", class: "dropzone well", id: "my_dropzone", html: { multipart: true, remote: true, authencity_token: true} do
        h4 Добавить телефоны клиентов
        p class="dz-message btn btn-success" style="width: 100%" Загрузить файлы csv
      div class="well"
        h4 Отправить уведомление пользователям
        = form_tag(send_broadcast_users_path, remote: true) do
          = text_field_tag :message, nil, placeholder: :Message, style: "width: 90%"
          = submit_tag 'Отправить уведомление', class: "btn btn-success", style: "width: 98%"

    div class='span9' style="margin-left: 0.5rem"
      div class="well" style="margin-left: 0; width: 95%;"
        h4 Список партнёров
        table class="table table-condensed table-hover table-bordered"
          thead
            tr
              th ID
              th Email
              th Название партнёра
              th Access token
              th Статус
              th Редактировать
              - if current_user.email == "davydenkov.mihail@gmail.com"
                th Удалить партнёра

          tbody
            - @users.each do |user|
              tr class=(user.status == "test" ? "not_valid" : "spl_positive")
                td= user.id
                td= user.email
                td= user.partner_source
                td= user.access_token
                td= (user.status == "test" ? "Тест" : "Активный")
                td= link_to 'Редактировать', edit_user_path(user)
                - if current_user.email == "davydenkov.mihail@gmail.com"
                  td= link_to 'Удалить партнёра', user, method: :delete, data: "confirm: 'Are you sure?'"

app/views/users/new.slim
div class='container'
  div class='row-fluid' id="users_form"
    div class='span3'
      div class="well"
        h4 Добавить партнёра
        = render 'form'

app/views/users/send_broadcast.js.erb
<% broadcast "/messages" do %>
    $("#main_container").html("<%= escape_javascript render 'show_message' %>");
<% end %>
$("#main_container")[0].reset();

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>