config/routes.rb
require 'sidekiq/web'

GetLead::Application.routes.draw do

  devise_for :users, except: [:create, :new, :update]

  match 'notifications/:id/hide', to: 'notifications#hide', as: 'hide_notification', via: :get

  resources :progresses
  resources :users do
    collection { post :file_uploads}
    collection { post :phones}
    collection { post :send_broadcast}
  end

  mount Sidekiq::Web, at: '/sidekiq'

  mount MongodbLogger::Server.new, :at => "/mongodb", :as => :mongodb
  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

  resources :reports

  resources :leads do
    collection { post :import }
    collection { get :import }
  end

  require 'api_constraints'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :leads
    end
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      resources :leads do
        collection { post :statistics }
      end
      patch '/leads/update' => 'leads_controller#update', as: 'update_leads'
    end
  end

   root :to => 'leads#index'

end

app/models/report.rb
# -*- encoding : utf-8 -*-
class Report < ActiveRecord::Base
end

app/controllers/reports_controller.rb
# -*- encoding : utf-8 -*-
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.where(user_id: current_user.id).order('created_at DESC').limit(3)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)



  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @report }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :user_id, :url)
    end
end

app/helpers/reports_helper.rb
# -*- encoding : utf-8 -*-
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<table>
<!--  <div id="nprogress" style="display: none">
    <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>
    <div class="bar" role="bar"><div class="peg" style="width: 0px;"></div></div>
  </div>-->
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td> <a href=<%= "#{report.url}"%>>Скачать</a></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user_id %>
</p>

<p>
  <strong>Url:</strong>
  <%= @report.url %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>