config/routes.rb
require 'sidekiq/web'

GetLead::Application.routes.draw do

  devise_for :users, except: [:create, :new, :update]

  match 'notifications/:id/hide', to: 'notifications#hide', as: 'hide_notification', via: :get

  resources :progresses
  resources :users do
    collection { post :file_uploads}
    collection { post :phones}
    collection { post :send_broadcast}
  end

  mount Sidekiq::Web, at: '/sidekiq'

  mount MongodbLogger::Server.new, :at => "/mongodb", :as => :mongodb
  mount MongodbLogger::Assets.instance, :at => "/mongodb/assets", :as => :mongodb_assets # assets

  resources :reports

  resources :leads do
    collection { post :import }
    collection { get :import }
  end

  require 'api_constraints'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1) do
      resources :leads
    end
    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true) do
      resources :leads do
        collection { post :statistics }
      end
      patch '/leads/update' => 'leads_controller#update', as: 'update_leads'
    end
  end

   root :to => 'leads#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<% if signed_in? %>
    <div class="navbar navbar-fixed-top" id="top_nav">
        <div class="navbar-inner">
            <div class="container">
            <a class="brand" style="cursor: default;font-weight: bold" href="/leads">Scoring</a>
                <ul class="nav pull-right">
                  <li> <%= link_to "Статистика по валидации", leads_path, method: "get" %> </li>
                  <li><%= link_to "Статистика по обработке", leads_path(processed_statistics: true), method: "get" %> </li>
                  <li><%= link_to "Выгрузки и заявки", leads_path(uploading_apps: true), method: "get" %> </li>
                  <% if current_user.admin? %>
                      <li><%= link_to "Управление партнёрами", users_path, method: "get" %> </li>
                  <% end %>
                  <li><%= link_to "Выйти", destroy_user_session_path, method: "delete" %> </li>
                </ul>
            </div>
        </div>
    </div>
<% end %>

<head>
  <title>Scoring</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
  <!-- javascript_include_tag "application", "http://scoring.banklife.org:9292/faye.js", "data-turbolinks-track" => true -->
  <%= csrf_meta_tags %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>

<body>
<div style="height: 2.85rem"> </div>

<%= render partial: 'users/show_message'%>

<%= yield %>
</body>

</html>